import type { Metadata } from "next";
import { PageHeader } from "@/components/layout/PageHeader";
import { RecommendedPortfolioPanel } from "@/components/recommended-portfolio/RecommendedPortfolioPanel";
import { getAnalysisProvider } from "@/providers/analysis-provider";

export const metadata: Metadata = {
  title: "Recommended Portfolio",
  description:
    "Primary and Hail Mary lineups from the Portfolio Intelligence Engine — display only.",
};

export default async function RecommendedPortfolioPage() {
  const viewModel = await getAnalysisProvider().getRecommendedPortfolio();

  return (
    <div className="space-y-6">
      <PageHeader
        title="Recommended Portfolio"
        description="Primary and Hail Mary lineups generated by the Portfolio Intelligence Engine."
      />
      <RecommendedPortfolioPanel viewModel={viewModel} />
    </div>
  );
}
