import type { RecommendedPortfolioViewModel } from "@/types/recommended-portfolio-view-model";

/** Placeholder view model — conforms to RecommendedPortfolioViewModel. Task 10.10 replaces provider only. */
export const recommendedPortfolioPlaceholder: RecommendedPortfolioViewModel = {
  portfolioOverview: {
    totalPortfolios: 6,
    primaryCount: 4,
    hailMaryCount: 2,
    generationTimestamp: null,
    portfolioStatus: "idle",
  },
  primaryPortfolios: [
    {
      lineupId: "primary-1",
      portfolioType: "primary",
      rank: 1,
      projectedPoints: null,
      confidence: null,
      risk: null,
      salaryUsed: null,
      ownership: null,
      correlation: null,
      leverage: null,
      explainabilitySummary: "Primary lineup #1 — placeholder explainability from PIE.",
    },
    {
      lineupId: "primary-2",
      portfolioType: "primary",
      rank: 2,
      projectedPoints: null,
      confidence: null,
      risk: null,
      salaryUsed: null,
      ownership: null,
      correlation: null,
      leverage: null,
      explainabilitySummary: "Primary lineup #2 — placeholder explainability from PIE.",
    },
    {
      lineupId: "primary-3",
      portfolioType: "primary",
      rank: 3,
      projectedPoints: null,
      confidence: null,
      risk: null,
      salaryUsed: null,
      ownership: null,
      correlation: null,
      leverage: null,
      explainabilitySummary: "Primary lineup #3 — placeholder explainability from PIE.",
    },
    {
      lineupId: "primary-4",
      portfolioType: "primary",
      rank: 4,
      projectedPoints: null,
      confidence: null,
      risk: null,
      salaryUsed: null,
      ownership: null,
      correlation: null,
      leverage: null,
      explainabilitySummary: "Primary lineup #4 — placeholder explainability from PIE.",
    },
  ],
  hailMaryPortfolios: [
    {
      lineupId: "hail-1",
      portfolioType: "hail_mary",
      rank: 1,
      ceiling: null,
      leverage: null,
      ownership: null,
      risk: null,
      contrarianRating: null,
      explainabilitySummary: "Hail Mary lineup #1 — placeholder contrarian thesis from PIE.",
    },
    {
      lineupId: "hail-2",
      portfolioType: "hail_mary",
      rank: 2,
      ceiling: null,
      leverage: null,
      ownership: null,
      risk: null,
      contrarianRating: null,
      explainabilitySummary: "Hail Mary lineup #2 — placeholder contrarian thesis from PIE.",
    },
  ],
  portfolioSummary: {
    portfolioGrade: null,
    overallConfidence: null,
    averageProjection: null,
    averageOwnership: null,
    averageSalary: null,
    averageRisk: null,
  },
  explainabilitySummary: [
    "Strong stacking opportunities (placeholder)",
    "High-confidence core players (placeholder)",
    "Balanced ownership profile (placeholder)",
    "Rookie value identified (placeholder)",
    "Tournament leverage available (placeholder)",
  ],
  generationMetadata: {
    analysisVersion: null,
    generationTime: null,
    simulationStatus: null,
    dataFreshness: null,
  },
  recommendations: [
    "Review Primary portfolio before submission (placeholder)",
    "Consider Hail Mary entries for large-field GPP (placeholder)",
  ],
};
